.PHONY: clean All

All:
	@echo "----------Building project:[ compe_lab_ex3 - Debug ]----------"
	@cd "compe_lab_ex3" && "$(MAKE)" -f  "compe_lab_ex3.mk"
clean:
	@echo "----------Cleaning project:[ compe_lab_ex3 - Debug ]----------"
	@cd "compe_lab_ex3" && "$(MAKE)" -f  "compe_lab_ex3.mk" clean
