.PHONY: clean All

All:
	@echo "----------Building project:[ OverLoadedConstructors - Debug ]----------"
	@cd "OverLoadedConstructors" && "$(MAKE)" -f  "OverLoadedConstructors.mk"
clean:
	@echo "----------Cleaning project:[ OverLoadedConstructors - Debug ]----------"
	@cd "OverLoadedConstructors" && "$(MAKE)" -f  "OverLoadedConstructors.mk" clean
