.PHONY: clean All

All:
	@echo "----------Building project:[ buscar_valor_abs - Debug ]----------"
	@cd "buscar_valor_abs" && "$(MAKE)" -f  "buscar_valor_abs.mk"
clean:
	@echo "----------Cleaning project:[ buscar_valor_abs - Debug ]----------"
	@cd "buscar_valor_abs" && "$(MAKE)" -f  "buscar_valor_abs.mk" clean
