.PHONY: clean All

All:
	@echo "----------Building project:[ compe_lab5 - Debug ]----------"
	@cd "compe_lab5" && "$(MAKE)" -f  "compe_lab5.mk"
clean:
	@echo "----------Cleaning project:[ compe_lab5 - Debug ]----------"
	@cd "compe_lab5" && "$(MAKE)" -f  "compe_lab5.mk" clean
