.PHONY: clean All

All:
	@echo "----------Building project:[ buscar_valor_abs3 - Debug ]----------"
	@cd "buscar_valor_abs3" && "$(MAKE)" -f  "buscar_valor_abs3.mk"
clean:
	@echo "----------Cleaning project:[ buscar_valor_abs3 - Debug ]----------"
	@cd "buscar_valor_abs3" && "$(MAKE)" -f  "buscar_valor_abs3.mk" clean
